// Chat y textos en el móvil (390 px).
import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
import assert from "node:assert/strict";
const BASE = process.env.E2E_BASE ?? "http://127.0.0.1:58000";
const SHOTS = `${process.env.E2E_DIR ?? "/tmp/another-e2e"}/shots`;
mkdirSync(SHOTS, { recursive: true });
const results = []; const ok = l => { results.push(l); console.log("PASS " + l); };
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const page = await ctx.newPage(); const errors = []; page.on("pageerror", e => errors.push(e.message));
const vis = name => page.getByRole("button", { name }).filter({ visible: true }).first();
await page.goto(BASE + "/");
await page.getByPlaceholder("Nombre de usuario").fill("dueno"); await page.getByPlaceholder("••••••••").fill("Sintetica-12345!");
await page.locator('button[type="submit"]').tap(); await page.waitForURL(/\/app/); await page.waitForTimeout(1500);
async function openGeneral() {
  if (await vis("Volver a los canales").isVisible().catch(() => false)) await vis("Volver a los canales").tap();
  if (await vis("Volver a la lista de servidores").isVisible().catch(() => false)) await vis("Volver a la lista de servidores").tap();
  await page.locator('button[title="Pruebas"]').first().tap(); await page.waitForTimeout(800);
  if (await vis("Volver a los canales").isVisible().catch(() => false)) await vis("Volver a los canales").tap();
  await page.locator('[data-testid^="channel-item-"]').filter({ hasText: "general-texto-1" }).tap();
  await page.getByText("Hola a todos").waitFor();
}
await openGeneral();
const boxes = await page.getByRole("button", { name: "Más acciones del mensaje" }).evaluateAll(els => els.filter(e => e.offsetParent).map(e => { const r = e.getBoundingClientRect(); return [r.top, r.bottom]; }));
assert.ok(boxes.length >= 4, `found ${boxes.length} message menus`);
for (let i = 1; i < boxes.length; i++) assert.ok(boxes[i][0] >= boxes[i - 1][1] - 0.5, `message menus ${i - 1} and ${i} overlap: ${JSON.stringify(boxes.slice(i - 1, i + 1))}`);
ok("message ⋮ buttons never overlap, even for consecutive short messages");
await page.getByRole("button", { name: "Más acciones del mensaje" }).filter({ visible: true }).nth(1).tap();
const expanded = () => page.locator('[aria-label="Más acciones del mensaje"][aria-expanded="true"]').count();
assert.equal(await expanded(), 1);
await page.getByText("¿Quién se conecta").tap();
await page.waitForTimeout(300);
assert.equal(await expanded(), 0, "action menu must close when tapping outside");
ok("the message action menu closes when tapping elsewhere");
await page.screenshot({ path: `${SHOTS}/chat-01-mensajes.png` });
await page.getByRole("button", { name: /Eventos/ }).filter({ visible: true }).first().tap();
const panel = page.getByRole("button", { name: "Cerrar eventos" }).locator("xpath=ancestor::div[contains(@class,'inset-y-0')][1]");
await panel.waitFor();
const style = await panel.evaluate(el => { const r = el.getBoundingClientRect(); return { bg: getComputedStyle(el).backgroundColor, width: r.width }; });
assert.ok(!/rgba\(.*,\s*0?\.\d+\)$/.test(style.bg), `events panel background is translucent: ${style.bg}`);
assert.ok(style.width >= 389, `events panel width ${style.width}`);
await page.screenshot({ path: `${SHOTS}/chat-02-eventos.png` });
ok("the events panel is opaque and full width on mobile");
await page.getByRole("button", { name: "Cerrar eventos" }).tap();
await vis("Buscar mensajes").tap();
const hint = page.getByText("Escribe al menos 2 caracteres para buscar");
assert.ok(!(await hint.evaluate(el => getComputedStyle(el).fontFamily)).toLowerCase().includes("mono"));
ok("the search hint uses the regular font");
await page.keyboard.press("Escape"); await page.mouse.click(5, 830);
await openGeneral();
await vis("Miembros").tap();
await page.getByText("Dueño", { exact: true }).filter({ visible: true }).nth(1).waitFor().catch(() => {});
assert.equal(await page.getByText("Owner", { exact: true }).count(), 0, "role label Owner is English");
ok("member roles are labelled in Spanish");
await vis("Cerrar miembros").tap().catch(() => {});
if (await vis("Volver a los canales").isVisible().catch(() => false)) await vis("Volver a los canales").tap();
await vis("Configuración del servidor").tap();
await page.getByText("PELIGRO").first().waitFor({ timeout: 5000 });
const offscreen = await page.evaluate(() => [...document.querySelectorAll("button")].filter(b => b.offsetParent && /^(ROLES|CANALES|CATEGORÍAS|MIEMBROS|APARIENCIA|INVITACIONES|.*SILENCIADOS|.*FILTROS|.*REPORTES|.*REGISTRO|.*PELIGRO)$/i.test(b.innerText.trim())).filter(b => { const r = b.getBoundingClientRect(); return r.right > innerWidth + 1 || r.left < -1; }).map(b => b.innerText.trim()));
assert.deepEqual(offscreen, [], `server settings tabs off screen: ${offscreen}`);
assert.equal(await page.getByText("manage channels").count(), 0);
await page.screenshot({ path: `${SHOTS}/chat-03-config-servidor.png` });
ok("all 11 server-settings tabs are visible without horizontal scrolling, permissions in Spanish");
assert.ok((await page.evaluate(() => document.scrollingElement.scrollWidth - innerWidth)) <= 0);
ok("no horizontal overflow");
assert.deepEqual(errors, []); ok("no page errors");
await browser.close(); console.log(`${results.length} checks passed`);
