export interface Emoji {
  char: string;
  names: string[];
  category: string;
}

export const EMOJI_CATEGORIES = [
  "Emoticonos y Emociones",
  "Personas y Cuerpo",
  "Animales y Naturaleza",
  "Comida y Bebida",
  "Actividades",
  "Viajes y Lugares",
  "Objetos",
  "Símbolos"
];

export const QUICK_EMOJIS = ["👍", "❤️", "😂", "😮", "😢", "🔥"];

export const EMOJI_CATALOG: Emoji[] = [
  { char: "😀", names: ["feliz", "sonrisa", "grinning", "cara sonriendo"], category: "Emoticonos y Emociones" },
  { char: "😃", names: ["feliz", "sonrisa grande", "smiley"], category: "Emoticonos y Emociones" },
  { char: "😄", names: ["feliz", "sonrisa con ojos cerrados", "smile"], category: "Emoticonos y Emociones" },
  { char: "😁", names: ["feliz", "sonrisa mostrando dientes", "grin"], category: "Emoticonos y Emociones" },
  { char: "😆", names: ["feliz", "sonrisa con los ojos arrugados", "laughing"], category: "Emoticonos y Emociones" },
  { char: "😅", names: ["feliz", "sonrisa con sudor", "sweat_smile"], category: "Emoticonos y Emociones" },
  { char: "😂", names: ["feliz", "lágrimas de alegría", "riendo", "joy"], category: "Emoticonos y Emociones" },
  { char: "🤣", names: ["feliz", "rodando por el suelo de risa", "rofl"], category: "Emoticonos y Emociones" },
  { char: "😊", names: ["feliz", "sonrisa ruborizada", "blush"], category: "Emoticonos y Emociones" },
  { char: "😇", names: ["feliz", "sonrisa con aureola", "ángel", "innocent"], category: "Emoticonos y Emociones" },
  { char: "🙂", names: ["feliz", "sonrisa ligera", "slightly_smiling"], category: "Emoticonos y Emociones" },
  { char: "🙃", names: ["feliz", "sonrisa al revés", "upside_down"], category: "Emoticonos y Emociones" },
  { char: "😉", names: ["feliz", "guiño", "wink"], category: "Emoticonos y Emociones" },
  { char: "😌", names: ["feliz", "cara aliviada", "relieved"], category: "Emoticonos y Emociones" },
  { char: "😍", names: ["amor", "cara con ojos de corazón", "enamorado", "heart_eyes"], category: "Emoticonos y Emociones" },
  { char: "🥰", names: ["amor", "cara con corazones", "enamorado", "smiling_face_with_3_hearts"], category: "Emoticonos y Emociones" },
  { char: "😘", names: ["amor", "beso", "kissing_heart"], category: "Emoticonos y Emociones" },
  { char: "😗", names: ["amor", "beso", "kissing"], category: "Emoticonos y Emociones" },
  { char: "😙", names: ["amor", "beso con ojos cerrados", "kissing_smiling_eyes"], category: "Emoticonos y Emociones" },
  { char: "😚", names: ["amor", "beso con ojos cerrados y rubor", "kissing_closed_eyes"], category: "Emoticonos y Emociones" },
  { char: "😋", names: ["comida", "saboreando", "yum"], category: "Emoticonos y Emociones" },
  { char: "😛", names: ["lengua", "sacando la lengua", "stuck_out_tongue"], category: "Emoticonos y Emociones" },
  { char: "😜", names: ["lengua", "guiño con lengua", "stuck_out_tongue_winking_eye"], category: "Emoticonos y Emociones" },
  { char: "🤪", names: ["loco", "cara de loco", "zany"], category: "Emoticonos y Emociones" },
  { char: "😝", names: ["lengua", "sacando la lengua con ojos arrugados", "stuck_out_tongue_closed_eyes"], category: "Emoticonos y Emociones" },
  { char: "🤑", names: ["dinero", "cara de dinero", "money_mouth"], category: "Emoticonos y Emociones" },
  { char: "🤗", names: ["abrazo", "cara abrazando", "hugs"], category: "Emoticonos y Emociones" },
  { char: "🤭", names: ["risa", "cara tapándose la boca", "hand_over_mouth"], category: "Emoticonos y Emociones" },
  { char: "🤫", names: ["silencio", "shh", "shushing"], category: "Emoticonos y Emociones" },
  { char: "🤔", names: ["pensando", "cara pensando", "thinking"], category: "Emoticonos y Emociones" },
  { char: "🤐", names: ["secreto", "cara con cremallera", "zipper_mouth"], category: "Emoticonos y Emociones" },
  { char: "🤨", names: ["duda", "cara con ceja levantada", "raised_eyebrow"], category: "Emoticonos y Emociones" },
  { char: "😐", names: ["serio", "cara neutral", "neutral"], category: "Emoticonos y Emociones" },
  { char: "😑", names: ["serio", "cara sin expresión", "expressionless"], category: "Emoticonos y Emociones" },
  { char: "😶", names: ["serio", "cara sin boca", "no_mouth"], category: "Emoticonos y Emociones" },
  { char: "😏", names: ["coqueto", "cara de suficiencia", "smirk"], category: "Emoticonos y Emociones" },
  { char: "😒", names: ["molesto", "cara de desagrado", "unamused"], category: "Emoticonos y Emociones" },
  { char: "🙄", names: ["molesto", "rodando los ojos", "roll_eyes"], category: "Emoticonos y Emociones" },
  { char: "😬", names: ["nervioso", "cara haciendo mueca", "grimacing"], category: "Emoticonos y Emociones" },
  { char: "🤥", names: ["mentira", "cara de pinocho", "lying"], category: "Emoticonos y Emociones" },
  { char: "😔", names: ["triste", "cara pensativa", "pensive"], category: "Emoticonos y Emociones" },
  { char: "😪", names: ["sueño", "cara con sueño", "sleepy"], category: "Emoticonos y Emociones" },
  { char: "🤤", names: ["hambre", "cara babeando", "drooling"], category: "Emoticonos y Emociones" },
  { char: "😴", names: ["sueño", "cara durmiendo", "sleeping"], category: "Emoticonos y Emociones" },
  { char: "😷", names: ["enfermo", "cara con mascarilla", "mask"], category: "Emoticonos y Emociones" },
  { char: "🤒", names: ["enfermo", "cara con termómetro", "thermometer"], category: "Emoticonos y Emociones" },
  { char: "🤕", names: ["enfermo", "cara con vendaje", "head_bandage"], category: "Emoticonos y Emociones" },
  { char: "🤢", names: ["enfermo", "cara de asco", "nauseated"], category: "Emoticonos y Emociones" },
  { char: "🤮", names: ["enfermo", "cara vomitando", "vomiting"], category: "Emoticonos y Emociones" },
  { char: "🤧", names: ["enfermo", "cara estornudando", "sneezing"], category: "Emoticonos y Emociones" },
  { char: "🥵", names: ["calor", "cara de calor", "hot"], category: "Emoticonos y Emociones" },
  { char: "🥶", names: ["frío", "cara de frío", "cold"], category: "Emoticonos y Emociones" },
  { char: "🥴", names: ["borracho", "cara mareada", "woozy"], category: "Emoticonos y Emociones" },
  { char: "😵", names: ["mareado", "cara mareada", "dizzy"], category: "Emoticonos y Emociones" },
  { char: "🤯", names: ["sorpresa", "cabeza explotando", "exploding_head"], category: "Emoticonos y Emociones" },
  { char: "🤠", names: ["vaquero", "cara de vaquero", "cowboy"], category: "Emoticonos y Emociones" },
  { char: "🥳", names: ["fiesta", "cara de fiesta", "partying"], category: "Emoticonos y Emociones" },
  { char: "😎", names: ["guay", "cara con gafas de sol", "sunglasses"], category: "Emoticonos y Emociones" },
  { char: "🤓", names: ["empollón", "cara de empollón", "nerd"], category: "Emoticonos y Emociones" },
  { char: "🧐", names: ["elegante", "cara con monóculo", "monocle"], category: "Emoticonos y Emociones" },
  { char: "😕", names: ["triste", "cara confundida", "confused"], category: "Emoticonos y Emociones" },
  { char: "😟", names: ["triste", "cara preocupada", "worried"], category: "Emoticonos y Emociones" },
  { char: "🙁", names: ["triste", "cara con el ceño fruncido", "slightly_frowning"], category: "Emoticonos y Emociones" },
  { char: "😮", names: ["sorpresa", "cara con la boca abierta", "open_mouth"], category: "Emoticonos y Emociones" },
  { char: "😯", names: ["sorpresa", "cara sorprendida", "hushed"], category: "Emoticonos y Emociones" },
  { char: "😲", names: ["sorpresa", "cara asombrada", "astonished"], category: "Emoticonos y Emociones" },
  { char: "😳", names: ["sorpresa", "cara ruborizada", "flushed"], category: "Emoticonos y Emociones" },
  { char: "🥺", names: ["triste", "cara suplicante", "pleading"], category: "Emoticonos y Emociones" },
  { char: "😦", names: ["triste", "cara con el ceño fruncido y la boca abierta", "frowning_with_open_mouth"], category: "Emoticonos y Emociones" },
  { char: "😧", names: ["triste", "cara angustiada", "anguished"], category: "Emoticonos y Emociones" },
  { char: "😨", names: ["miedo", "cara asustada", "fearful"], category: "Emoticonos y Emociones" },
  { char: "😰", names: ["miedo", "cara con sudor frío", "cold_sweat"], category: "Emoticonos y Emociones" },
  { char: "😥", names: ["triste", "cara triste pero aliviada", "disappointed_relieved"], category: "Emoticonos y Emociones" },
  { char: "😢", names: ["triste", "cara llorando", "cry"], category: "Emoticonos y Emociones" },
  { char: "😭", names: ["triste", "cara llorando a mares", "sob"], category: "Emoticonos y Emociones" },
  { char: "😱", names: ["miedo", "cara gritando de miedo", "scream"], category: "Emoticonos y Emociones" },
  { char: "😖", names: ["triste", "cara confundida", "confounded"], category: "Emoticonos y Emociones" },
  { char: "😣", names: ["triste", "cara perseverante", "persevere"], category: "Emoticonos y Emociones" },
  { char: "😞", names: ["triste", "cara decepcionada", "disappointed"], category: "Emoticonos y Emociones" },
  { char: "😓", names: ["triste", "cara con sudor frío", "sweat"], category: "Emoticonos y Emociones" },
  { char: "😩", names: ["cansado", "cara agotada", "weary"], category: "Emoticonos y Emociones" },
  { char: "😫", names: ["cansado", "cara cansada", "tired"], category: "Emoticonos y Emociones" },
  { char: "🥱", names: ["sueño", "cara bostezando", "yawning"], category: "Emoticonos y Emociones" },
  { char: "😤", names: ["enfadado", "cara con humo en la nariz", "triumph"], category: "Emoticonos y Emociones" },
  { char: "😡", names: ["enfadado", "cara roja de enfado", "rage"], category: "Emoticonos y Emociones" },
  { char: "😠", names: ["enfadado", "cara de enfado", "angry"], category: "Emoticonos y Emociones" },
  { char: "🤬", names: ["enfadado", "cara con símbolos en la boca", "cursing"], category: "Emoticonos y Emociones" },
  { char: "😈", names: ["diablo", "cara sonriente con cuernos", "smiling_imp"], category: "Emoticonos y Emociones" },
  { char: "👿", names: ["diablo", "cara de diablo", "imp"], category: "Emoticonos y Emociones" },
  { char: "💀", names: ["calavera", "muerto", "skull"], category: "Emoticonos y Emociones" },
  { char: "💩", names: ["caca", "mierda", "poop"], category: "Emoticonos y Emociones" },
  { char: "🤡", names: ["payaso", "clown"], category: "Emoticonos y Emociones" },
  { char: "👹", names: ["ogro", "demonio", "japanese_ogre"], category: "Emoticonos y Emociones" },
  { char: "👺", names: ["duende", "demonio", "japanese_goblin"], category: "Emoticonos y Emociones" },
  { char: "👻", names: ["fantasma", "ghost"], category: "Emoticonos y Emociones" },
  { char: "👽", names: ["alien", "extraterrestre", "alien"], category: "Emoticonos y Emociones" },
  { char: "👾", names: ["alien", "monstruo alienígena", "space_invader"], category: "Emoticonos y Emociones" },
  { char: "🤖", names: ["robot", "robot"], category: "Emoticonos y Emociones" },
  { char: "❤️", names: ["corazón rojo", "amor", "heart"], category: "Símbolos" },
  { char: "🧡", names: ["corazón naranja", "amor", "orange_heart"], category: "Símbolos" },
  { char: "💛", names: ["corazón amarillo", "amor", "yellow_heart"], category: "Símbolos" },
  { char: "💚", names: ["corazón verde", "amor", "green_heart"], category: "Símbolos" },
  { char: "💙", names: ["corazón azul", "amor", "blue_heart"], category: "Símbolos" },
  { char: "💜", names: ["corazón morado", "amor", "purple_heart"], category: "Símbolos" },
  { char: "🖤", names: ["corazón negro", "amor", "black_heart"], category: "Símbolos" },
  { char: "🤍", names: ["corazón blanco", "amor", "white_heart"], category: "Símbolos" },
  { char: "🤎", names: ["corazón marrón", "amor", "brown_heart"], category: "Símbolos" },
  { char: "💔", names: ["corazón roto", "desamor", "broken_heart"], category: "Símbolos" },
  { char: "✨", names: ["brillos", "estrellas", "sparkles"], category: "Símbolos" },
  { char: "🔥", names: ["fuego", "caliente", "fire"], category: "Símbolos" },
  { char: "💯", names: ["cien", "perfecto", "100"], category: "Símbolos" },
  { char: "🐶", names: ["perro", "perrito", "dog"], category: "Animales y Naturaleza" },
  { char: "🐱", names: ["gato", "gatito", "cat"], category: "Animales y Naturaleza" },
  { char: "🐭", names: ["ratón", "mouse"], category: "Animales y Naturaleza" },
  { char: "🐹", names: ["hámster", "hamster"], category: "Animales y Naturaleza" },
  { char: "🐰", names: ["conejo", "bunny", "rabbit"], category: "Animales y Naturaleza" },
  { char: "🦊", names: ["zorro", "fox"], category: "Animales y Naturaleza" },
  { char: "🐻", names: ["oso", "bear"], category: "Animales y Naturaleza" },
  { char: "🐼", names: ["panda", "panda"], category: "Animales y Naturaleza" },
  { char: "🐨", names: ["koala", "koala"], category: "Animales y Naturaleza" },
  { char: "🐯", names: ["tigre", "tiger"], category: "Animales y Naturaleza" },
  { char: "🦁", names: ["león", "lion"], category: "Animales y Naturaleza" },
  { char: "🐮", names: ["vaca", "cow"], category: "Animales y Naturaleza" },
  { char: "🐷", names: ["cerdo", "cerdito", "pig"], category: "Animales y Naturaleza" },
  { char: "🐸", names: ["rana", "sapo", "frog"], category: "Animales y Naturaleza" },
  { char: "🐵", names: ["mono", "monkey"], category: "Animales y Naturaleza" },
  { char: "🍎", names: ["manzana roja", "fruta", "apple"], category: "Comida y Bebida" },
  { char: "🍌", names: ["plátano", "banana", "fruta"], category: "Comida y Bebida" },
  { char: "🍉", names: ["sandía", "fruta", "watermelon"], category: "Comida y Bebida" },
  { char: "🍇", names: ["uvas", "fruta", "grapes"], category: "Comida y Bebida" },
  { char: "🍓", names: ["fresa", "fruta", "strawberry"], category: "Comida y Bebida" },
  { char: "🍔", names: ["hamburguesa", "comida rápida", "burger"], category: "Comida y Bebida" },
  { char: "🍟", names: ["patatas fritas", "comida rápida", "fries"], category: "Comida y Bebida" },
  { char: "🍕", names: ["pizza", "pizza"], category: "Comida y Bebida" },
  { char: "🌮", names: ["taco", "comida mexicana", "taco"], category: "Comida y Bebida" },
  { char: "🍣", names: ["sushi", "comida japonesa", "sushi"], category: "Comida y Bebida" },
  { char: "🍺", names: ["cerveza", "bebida", "beer"], category: "Comida y Bebida" },
  { char: "☕", names: ["café", "bebida caliente", "coffee"], category: "Comida y Bebida" },
  { char: "👋", names: ["hola", "adiós", "mano saludando", "wave"], category: "Personas y Cuerpo" },
  { char: "🤚", names: ["mano levantada", "raised_back_of_hand"], category: "Personas y Cuerpo" },
  { char: "🖐️", names: ["mano abierta", "raised_hand_with_fingers_splayed"], category: "Personas y Cuerpo" },
  { char: "✋", names: ["mano levantada", "raised_hand"], category: "Personas y Cuerpo" },
  { char: "🖖", names: ["saludo vulcano", "spock", "vulcan"], category: "Personas y Cuerpo" },
  { char: "👌", names: ["bien", "ok", "perfecto", "ok_hand"], category: "Personas y Cuerpo" },
  { char: "✌️", names: ["paz", "victoria", "v", "peace"], category: "Personas y Cuerpo" },
  { char: "🤞", names: ["suerte", "dedos cruzados", "crossed_fingers"], category: "Personas y Cuerpo" },
  { char: "🤟", names: ["te quiero", "lenguaje de signos", "love_you"], category: "Personas y Cuerpo" },
  { char: "🤘", names: ["rock", "cuernos", "metal", "horns"], category: "Personas y Cuerpo" },
  { char: "🤙", names: ["llamada", "shaka", "call_me"], category: "Personas y Cuerpo" },
  { char: "👈", names: ["izquierda", "apuntando izquierda", "point_left"], category: "Personas y Cuerpo" },
  { char: "👉", names: ["derecha", "apuntando derecha", "point_right"], category: "Personas y Cuerpo" },
  { char: "👆", names: ["arriba", "apuntando arriba", "point_up_2"], category: "Personas y Cuerpo" },
  { char: "👇", names: ["abajo", "apuntando abajo", "point_down"], category: "Personas y Cuerpo" },
  { char: "👍", names: ["bien", "me gusta", "pulgar arriba", "thumbsup"], category: "Personas y Cuerpo" },
  { char: "👎", names: ["mal", "no me gusta", "pulgar abajo", "thumbsdown"], category: "Personas y Cuerpo" },
  { char: "✊", names: ["puño", "fist"], category: "Personas y Cuerpo" },
  { char: "👊", names: ["puñetazo", "punch"], category: "Personas y Cuerpo" },
  { char: "🤛", names: ["puño izquierdo", "left_facing_fist"], category: "Personas y Cuerpo" },
  { char: "🤜", names: ["puño derecho", "right_facing_fist"], category: "Personas y Cuerpo" },
  { char: "👏", names: ["aplauso", "aplausos", "clap"], category: "Personas y Cuerpo" },
  { char: "🙌", names: ["celebración", "manos levantadas", "raised_hands"], category: "Personas y Cuerpo" },
  { char: "👐", names: ["manos abiertas", "open_hands"], category: "Personas y Cuerpo" },
  { char: "🤲", names: ["manos juntas", "palms_up_together"], category: "Personas y Cuerpo" },
  { char: "🤝", names: ["apretón de manos", "trato", "handshake"], category: "Personas y Cuerpo" },
  { char: "🙏", names: ["por favor", "gracias", "rezar", "pray"], category: "Personas y Cuerpo" }
];
