import { pgTable, serial, integer, text, varchar, timestamp, foreignKey, unique } from "drizzle-orm/pg-core";
import { users } from "./users";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
export const dmGroups = pgTable("dm_groups", { id: serial().primaryKey().notNull(), name: varchar({ length: 100 }), ownerId: integer("owner_id").notNull(), createdAt: timestamp("created_at", { mode: "date" }).defaultNow() }, t => [foreignKey({ columns: [t.ownerId], foreignColumns: [users.id], name: "dm_groups_owner_id_fkey" }).onDelete("cascade")]);
export const dmGroupMembers = pgTable("dm_group_members", { id: serial().primaryKey().notNull(), groupId: integer("group_id").notNull(), userId: integer("user_id").notNull(), joinedAt: timestamp("joined_at", { mode: "date" }).defaultNow() }, t => [foreignKey({ columns: [t.groupId], foreignColumns: [dmGroups.id], name: "dm_group_members_group_id_fkey" }).onDelete("cascade"), foreignKey({ columns: [t.userId], foreignColumns: [users.id], name: "dm_group_members_user_id_fkey" }).onDelete("cascade"), unique("dm_group_members_group_id_user_id_key").on(t.groupId, t.userId)]);
export const dmGroupMessages = pgTable("dm_group_messages", { id: serial().primaryKey().notNull(), groupId: integer("group_id").notNull(), userId: integer("user_id").notNull(), content: text().notNull(), iv: text().notNull(), createdAt: timestamp("created_at", { mode: "date" }).defaultNow(), deletedAt: timestamp("deleted_at", { mode: "date" }) }, t => [foreignKey({ columns: [t.groupId], foreignColumns: [dmGroups.id], name: "dm_group_messages_group_id_fkey" }).onDelete("cascade"), foreignKey({ columns: [t.userId], foreignColumns: [users.id], name: "dm_group_messages_user_id_fkey" }).onDelete("cascade")]);
export const dmGroupsTable = dmGroups;
export const dmGroupMembersTable = dmGroupMembers;
export const dmGroupMessagesTable = dmGroupMessages;
export const insertDmGroupSchema = createInsertSchema(dmGroups).omit({ id: true, createdAt: true });
export const insertDmGroupMemberSchema = createInsertSchema(dmGroupMembers).omit({ id: true, joinedAt: true });
export const insertDmGroupMessageSchema = createInsertSchema(dmGroupMessages).omit({ id: true, createdAt: true, deletedAt: true });
export type DmGroup = typeof dmGroups.$inferSelect;
export type InsertDmGroup = z.infer<typeof insertDmGroupSchema>;
export type DmGroupMember = typeof dmGroupMembers.$inferSelect;
export type InsertDmGroupMember = z.infer<typeof insertDmGroupMemberSchema>;
export type DmGroupMessage = typeof dmGroupMessages.$inferSelect;
export type InsertDmGroupMessage = z.infer<typeof insertDmGroupMessageSchema>;