import { pgTable, serial, integer, text, varchar, timestamp, jsonb, foreignKey, unique, index } from "drizzle-orm/pg-core";
import { users } from "./users";
import { servers } from "./servers";
import { messages } from "./messages";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
export const messageReports = pgTable("message_reports", { id: serial().primaryKey().notNull(), messageId: integer("message_id").notNull(), reporterId: integer("reporter_id").notNull(), serverId: integer("server_id"), reason: text().notNull(), status: varchar({ length: 20 }).default("pending").notNull(), resolvedById: integer("resolved_by_id"), resolvedAt: timestamp("resolved_at", { mode: "date" }), createdAt: timestamp("created_at", { mode: "date" }).defaultNow() }, t => [foreignKey({ columns: [t.messageId], foreignColumns: [messages.id], name: "message_reports_message_id_fkey" }).onDelete("cascade"), foreignKey({ columns: [t.reporterId], foreignColumns: [users.id], name: "message_reports_reporter_id_fkey" }).onDelete("cascade"), foreignKey({ columns: [t.resolvedById], foreignColumns: [users.id], name: "message_reports_resolved_by_id_fkey" }).onDelete("set null"), foreignKey({ columns: [t.serverId], foreignColumns: [servers.id], name: "message_reports_server_id_fkey" }).onDelete("cascade"), unique("message_reports_message_id_reporter_id_key").on(t.messageId, t.reporterId)]);
export const wordFilters = pgTable("word_filters", { id: serial().primaryKey().notNull(), serverId: integer("server_id").notNull(), word: varchar({ length: 200 }).notNull(), createdById: integer("created_by_id"), createdAt: timestamp("created_at", { mode: "date" }).defaultNow() }, t => [foreignKey({ columns: [t.createdById], foreignColumns: [users.id], name: "word_filters_created_by_id_fkey" }).onDelete("set null"), foreignKey({ columns: [t.serverId], foreignColumns: [servers.id], name: "word_filters_server_id_fkey" }).onDelete("cascade"), unique("word_filters_server_id_word_key").on(t.serverId, t.word)]);
export const serverMutes = pgTable("server_mutes", { id: serial().primaryKey().notNull(), serverId: integer("server_id").notNull(), userId: integer("user_id").notNull(), mutedById: integer("muted_by_id"), expiresAt: timestamp("expires_at", { mode: "date" }).notNull(), reason: text(), createdAt: timestamp("created_at", { mode: "date" }).defaultNow() }, t => [foreignKey({ columns: [t.mutedById], foreignColumns: [users.id], name: "server_mutes_muted_by_id_fkey" }).onDelete("set null"), foreignKey({ columns: [t.serverId], foreignColumns: [servers.id], name: "server_mutes_server_id_fkey" }).onDelete("cascade"), foreignKey({ columns: [t.userId], foreignColumns: [users.id], name: "server_mutes_user_id_fkey" }).onDelete("cascade"), unique("server_mutes_server_id_user_id_key").on(t.serverId, t.userId)]);
export const auditLog = pgTable("audit_log", { id: serial().primaryKey().notNull(), serverId: integer("server_id").notNull(), actorId: integer("actor_id"), targetUserId: integer("target_user_id"), action: varchar({ length: 60 }).notNull(), detail: jsonb().default({}), createdAt: timestamp("created_at", { mode: "date" }).defaultNow() }, t => [index("idx_audit_log_server").using("btree", t.serverId.asc().nullsLast(), t.createdAt.desc().nullsFirst()), foreignKey({ columns: [t.actorId], foreignColumns: [users.id], name: "audit_log_actor_id_fkey" }).onDelete("set null"), foreignKey({ columns: [t.serverId], foreignColumns: [servers.id], name: "audit_log_server_id_fkey" }).onDelete("cascade"), foreignKey({ columns: [t.targetUserId], foreignColumns: [users.id], name: "audit_log_target_user_id_fkey" }).onDelete("set null")]);
export const messageReportsTable = messageReports;
export const wordFiltersTable = wordFilters;
export const serverMutesTable = serverMutes;
export const auditLogTable = auditLog;
export const insertMessageReportSchema = createInsertSchema(messageReports).omit({ id: true, createdAt: true });
export const insertWordFilterSchema = createInsertSchema(wordFilters).omit({ id: true, createdAt: true });
export const insertServerMuteSchema = createInsertSchema(serverMutes).omit({ id: true, createdAt: true });
export const insertAuditLogSchema = createInsertSchema(auditLog).omit({ id: true, createdAt: true });
export type MessageReport = typeof messageReports.$inferSelect;
export type InsertMessageReport = z.infer<typeof insertMessageReportSchema>;
export type WordFilter = typeof wordFilters.$inferSelect;
export type InsertWordFilter = z.infer<typeof insertWordFilterSchema>;
export type ServerMute = typeof serverMutes.$inferSelect;
export type InsertServerMute = z.infer<typeof insertServerMuteSchema>;
export type AuditLog = typeof auditLog.$inferSelect;
export type InsertAuditLog = z.infer<typeof insertAuditLogSchema>;