import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { servers, serverMembers, serverRoles, serverMemberRoles, serverInvites } from "./introspected";
export const serversTable = servers;
export const serverMembersTable = serverMembers;
export const serverRolesTable = serverRoles;
export const serverMemberRolesTable = serverMemberRoles;
export const serverInvitesTable = serverInvites;
export const insertServerSchema = createInsertSchema(serversTable).omit({ id: true, createdAt: true });
export const insertServerMemberSchema = createInsertSchema(serverMembersTable).omit({ id: true, joinedAt: true });
export const insertServerRoleSchema = createInsertSchema(serverRolesTable).omit({ id: true, createdAt: true });
export const insertServerInviteSchema = createInsertSchema(serverInvitesTable).omit({ id: true, createdAt: true });
export type InsertServer = z.infer<typeof insertServerSchema>;
export type Server = typeof serversTable.$inferSelect;
export type InsertServerMember = z.infer<typeof insertServerMemberSchema>;
export type ServerMember = typeof serverMembersTable.$inferSelect;
export type InsertServerRole = z.infer<typeof insertServerRoleSchema>;
export type ServerRole = typeof serverRolesTable.$inferSelect;
export type ServerMemberRole = typeof serverMemberRolesTable.$inferSelect;
export type ServerInvite = typeof serverInvitesTable.$inferSelect;
export type InsertServerInvite = z.infer<typeof insertServerInviteSchema>;